[package]
name = "nuphy-music"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
crossterm = "0.27.0"
hidapi = "2.6.1"
ratatui = "0.26.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
